apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "theia-carlos.fullname" . }}
  labels:
    { { - include "theia-carlos.labels" . | nindent 4 } }
  namespace: {{ include "theia-carlos.fullname" . }}
{{-with: .Values.configMapData}}
data:
  {{- toYaml . | nindent 2}}
{{- end}}
